baseURL: "https://claydav.is/" 
title: Clay Davis
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: clay_cd

taxonomies:
    tag: tags
    category: categories
    
menu:
    main:
        - name: Publications
          url: /publications/
          weight: 1
        - name: CV
          url: /cv
          weight: 2
        - name: Syllabi
          url: /syllabi/
          weight: 3
        - name: Office hours
          url: /officehours/
          weight: 4

params:
    description: "I am a PhD candidate in sociology and Mellon Cluster Fellow in science studies at Northwestern University."
    author: Clay Davis
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Clay Davis
          subtitle: "I am a PhD candidate in sociology and Mellon Cluster Fellow in science studies at <a href='https://sociology.northwestern.edu/people/graduate-students/profiles/clay-davis.html' style='color:#77b59e'>Northwestern University</a>. My interests lie in the tensions between democracy and expertise. In particular, I study how credentialed experts&#8212;and the health social movements that challenge them&#8212;use epistemic tools like randomized controlled trials (the focus of my first paper in <i><a href='/3S1' style='color:#77b59e'>Social Studies of Science</a></i>), databanks (as I discuss in my recent <i><a href='/3S2' style='color:#77b59e'>Social Studies of Science</a></i> paper), and meta-analysis (the topic of my dissertation) as sources of political power. <br><br> Check out <a href='https://www.tgs.northwestern.edu/about/our-people/spotlight/clay-davis-hehim.html' style='color:#77b59e'>my profile</a> in Northwestern's <i>TGS Spotlight</i>.</br></br>"
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Clay Davis
          buttons:
            - name: Publications
              url: /publications/
            - name: CV
              url: /cv/
            - name: Syllabi
              url: /syllabi/
            - name: Office hours
              url: /officehours/
              
    socialIcons:
        - name: Email
          url: mailto:cdavis@u.northwestern.edu
        - name: twitter
          url: https://twitter.com/clay_cd
        - name: bluesky
          url: https://bsky.app/profile/claydav.is
        - name: orcid
          url: https://orcid.org/0000-0002-3443-3512
        - name: google scholar
          url: https://scholar.google.com/citations?hl=en&user=ZuazMDwAAAAJ
          
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Clay Davis"
      icon: /favicon-32x32.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
